//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Integrado
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data;

    public partial class aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aluno()
        {
            this.responsaveis = new HashSet<responsaveis>();
        }

        public int numero_matricula { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string rg { get; set; }
        public string dt_nascimento { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string rua { get; set; }
        public int numero { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string situacao_matricula { get; set; }
        public string cd_turma { get; set; }

        public virtual turma turma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<responsaveis> responsaveis { get; set; }


        public bool ValidaAluno(aluno aluno)
        {
            using (var context = new gestaoescolarEntities())
            {
                var valida = context.aluno.Where(x => x.cpf == aluno.cpf);

                var count = valida.Count();
                if (count != 0)
                {
                    return false;
                }
                return true;
            }
        }
        public void CadastrarAluno(aluno aluno)
        {
            using (var context = new gestaoescolarEntities())
            {
                
                context.aluno.Add(aluno);

                context.SaveChanges();

            }

        }
        public void CadastrarRespAluno(aluno aluno,responsaveis responsaveis)
        {
            using (var context = new gestaoescolarEntities())
            {

                aluno.responsaveis.Add(responsaveis);
                context.SaveChanges();

            }

        }
        public string RetornarMatricula(aluno al)
        {
            using (var context = new gestaoescolarEntities())
            {
                var alunos = context.aluno.Select(x => new { x.numero_matricula, x.cpf }).Where(x => x.cpf == al.cpf).ToList();
                
                var str = alunos[0].numero_matricula.ToString();
                return str;
            }


        }
    }
}
