//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Integrado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestaoescolarEntities : DbContext
    {
        public gestaoescolarEntities()
            : base("name=gestaoescolarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluno> aluno { get; set; }
        public virtual DbSet<professor> professor { get; set; }
        public virtual DbSet<responsaveis> responsaveis { get; set; }
        public virtual DbSet<turma> turma { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }

    }
}
