//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Integrado
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public int cd_notas { get; set; }
        public Nullable<float> prova_1 { get; set; }
        public Nullable<float> prova_2 { get; set; }
        public string situacao_final { get; set; }
        public int numero_matricula { get; set; }
    
        public virtual aluno aluno { get; set; }
    }
}
