//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Integrado
{
    using System;
    using System.Collections.Generic;
    
    public partial class professor
    {
        public int cod_reg { get; set; }
        public string nome { get; set; }
        public string periodo { get; set; }
        public string cd_turma { get; set; }
    
        public virtual turma turma { get; set; }
    }
}
